[package]
name = "sakubun"
version = "0.1.0"
authors = ["aravk <aravkasi@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1.4"
rand = "0.8.3"
rocket = "0.4.7"
rocket_contrib = { version = "0.4.7", features = ["tera_templates"] }
multipart = "0.17.1"
zip = { version = "0.5.9", default-features = false, features = ["deflate"] }
rusqlite = { version = "0.24.2", features = ["bundled"] }
uuid = { version = "0.8.2", features = ["v4"] }
csv = "1.1"
